### ISSUE TITLE
Magento EE 2.2.5 config of yml file seems skipped

### ISSUE THREAD

**Issue by giuseppemorelli** [webgriffe/module-config-override#5]
I have this `default-dev.yml' file:

```
msp_devtools:
  general:
    enabled: true
    authorized_ranges: "0.0.0.0/0, 172.16.244.0/24, 172.16.244.10"
  phpstorm:
    enabled: true
    port: "8091"
```

But magento seems getting the data saved in the db.

![image](https://user-images.githubusercontent.com/1280769/46151967-45ebb100-c270-11e8-8cd6-f166de203320.png)

![image](https://user-images.githubusercontent.com/1280769/46151950-3704fe80-c270-11e8-85bc-7b3ea901fda1.png)

So in this case (example MSP_DevTools) the config used is from database and the extension is disabled.

Maybe an issue only for EE version?
